name: Déploiement           # Nom du workflow
on: 
    push                    # Événement(s)
env:
    USERNAME: dansaj14
    IMAGE_NAME: deer
jobs:
    build-docker-image:     # Nom du job
        runs-on: ubuntu-latest  # OS utilisé pour executé le job
        steps:                  # Suite de commandes / tâches à effectuer
            - name: Check out code
              uses: actions/checkout@v3
            - run: docker login -u $USERNAME -p $PASSWORD
              env:
                PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
            - run: docker build -t $USERNAME/$IMAGE_NAME .
            - run: docker push $USERNAME/$IMAGE_NAME
    PushContainerReadme:
        runs-on: ubuntu-latest
        name: Push README to Docker Hub
        steps:
          - name: git checkout
            uses: actions/checkout@v2
          - name: push README to Dockerhub
            uses: christian-korneck/update-container-description-action@v1
            env:
              DOCKER_USER: my-user
              DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
            with:
              destination_container_repo: my-user/my-repo
              provider: dockerhub
              short_description: 'my short description 😊'
              readme_file: 'README.md'